export { HomePage } from "./public/HomePage";
export { CoursesPage } from "./public/CoursesPage";
export { default as LoginPage } from "./auth/LoginPage";
export { default as SignUpPage } from "./auth/SignUpPage";
export { default as SettingsPage } from "./user/SettingsPage";
export { default as PurchasesPage } from "./user/PurchasesPage";
export { default as CertificatesPage } from "./user/CertificatesPage";
export { default as CourseDetailPage } from "./public/CourseDetailPage";
export { default as VideoLearningPage } from "./public/VideoLearningPage";
export { default as AdminDashboard } from "./admin/AdminDashboard";
export { default as AdminCourses } from "./admin/AdminCourses";
export { default as AdminUsers } from "./admin/AdminUsers";
export { default as AdminReports } from "./admin/AdminReports";
export { default as AdminCourseNew } from "./admin/AdminCourseNew";
export { default as QuizPage } from "./public/QuizPage";
export { default as CodePracticePage } from "./public/CodePracticePage";
